name: Docker build
on: 
  push:
    branches:
      - main

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build PHP
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USR }}
          password: ${{ secrets.GHCR_PAT }}
          path: php/
          image: php
          tag: "5.6"
          cache: true
          cache_registry: cache