name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build iamge php
      run: 
        docker build --pull --rm -f "php/Dockerfile" --tag ghcr.io/zuzustack/php5.6:latest "php"
        docker run ghcr.io/zuzustack/php5.6:latest
        docker push ghcr.io/zuzustack/php5.6:latest

