name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build image php
      run: 
        docker build --pull --rm -f "php/Dockerfile" --tag ghcr.io/${{ github.actor }}/php5.6:latest "php" &&
        docker push ghcr.io/${{ github.actor }}/php5.6:latest

