name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build iamge php
      run: docker build ./php --file Dockerfile --tag php5.6:latest
